### ISSUE TITLE
ability to pick a single piece of media to show

### ISSUE THREAD

**Issue by chrisdrackett** [spalt/EO1#1]
It would be nice to be able to show just a single piece or media or a small collection of media. I wonder if its possible via setting up something like a "Live" album and having the app show whatever is in this album

**Comment by spalt** [comment]
This can be accomplished now using the "partner app" and the Flickr app w/"tags".  Let me know if you had something else in mind!

**Comment by chrisdrackett** [comment]
It would be great if I could access private photos and videos, vs having to have everything public on flickr. I still haven't been able to get the tags working, but looking at the code I think it only works currently with public media
