### ISSUE TITLE
Dark spot at the top center

### ISSUE THREAD

**Issue by Marotte** [spalt/EO1#12]
After launching the app, a dark spot appears at the top of screen, horizontally centered, like if one of the led backlighting the screen was turned off.

It remains even when switching to another app (e.g. firefox) or when the app crashes, but disappears when the EO1 is rebooted.

**Comment by spalt** [comment]
@Marotte thanks for the note, i can't imagine my app has anything to do with that issue.  sounds like perhaps a problem with your hardware, which, as you probably know, is no longer supported by the company that bought Electric Objects.
