### ISSUE TITLE
Apk download stuck in queued state

### ISSUE THREAD

**Issue by rgudla** [spalt/EO1#13]
![PXL_20230901_082934044.jpg](https://github.com/spalt/EO1/assets/6809656/bd501f23-17ba-4408-81c9-705974af92d8)

First of all, thank you for giving me hope to revive eo1.

I got the USB adapter and connected it to the mouse. Used it to connect to wifi.

Then, using the keyboard shortcut, I opened the browser and opened the GitHub URL.

When clicked on apk link, it says starting download but queued in the background. 

Any suggestions? Please help.

**Comment by spalt** [comment]
Thanks, I've heard this from a few people, the old browser on the device doesn't like github downloads all the time, apparently. I've added a link to a mirror on the main github page that I will attempt to keep updated!

**Comment by rgudla** [comment]
Amazing. Download worked over the mirror. App worked perfectly through flickr. Thanks for your efforts!

**Comment by aphex3k** [comment]
What is the setup for the mirror that you changed so APKs don't get stuck?

**Comment by aphex3k** [comment]
Sorry, I should've been more precise. I'm attempting to host a similar APK (fork of this repo) on my own nginx server but the downloads get stuck over https. I solved my issue by downloading them via HTTP...

However, TLS seems to be an issue with KitKat across the board as my retrofit api client is unable to connect to a secure API hosted on my own server.

I'm in the middle of finding out, what is the highest supported TLS configuration on KitKat and how I can change my NGINX setup so they have at least one matching protocol/cipher combination. BUT IT IS TEDIOUS!

**Comment by spalt** [comment]
@aphex3k understood!  i ran into a similar problem, fixed using an older version of retrofit -- 2.6.0 to be specific.  anything newer or older didn't work.   good luck!

**Comment by aphex3k** [comment]
I solved my TLS issues with the factory posted in this PR: https://github.com/square/okhttp/issues/2372
