### ISSUE TITLE
Brightness setting reverts after waking from Quiet Hours

### ISSUE THREAD

**Issue by christianboyle** [spalt/EO1#15]
Having set the brightness last night, I awoke to find it back to 100%. Yet, it seems like the setting is still correct in the partner app.

Maybe there needs to be an existence check for the brightness setting prior to re-enabling the display?

Current settings:

![2023-09-07_08-41-20AM](https://github.com/spalt/EO1/assets/1605754/a04b140d-5d4a-459c-8030-3ef3d32b033b)

**Comment by spalt** [comment]
@christianboyle i will fix this.. thank you!

**Comment by JDogg016** [comment]
Any update on this fix?

**Comment by spalt** [comment]
@JDogg016 @christianboyle I was trying to get this in with a few other things, but the other things aren't quite ready yet.  I shelved those and released a version with just this, it's available now.

**Comment by JDogg016** [comment]
Thank you!  My screen had been ‘auto dimming’ for several days now.  Dumb question, how do I update?  Do I need to redownload the apk?

From: Dan Finkelstein ***@***.***>
Date: Thursday, September 28, 2023 at 9:49 AM
To: spalt/EO1 ***@***.***>
Cc: JDogg016 ***@***.***>, Mention ***@***.***>
Subject: Re: [spalt/EO1] Brightness setting reverts after waking from Quiet Hours (Issue #15)

@JDogg016<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JDogg016&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EKkWq-PIwclXaajKqY3DZrDQ9bdhdNRJkYhOAtxknFo&m=UcZXQ70t8qQukcYZ5YZ0J6v1gXlLLzvDhdQh1HtNB3mmMJPL5Al2C362p79qFDPp&s=5yCEQs--81Mv5Dq9oqke1YMBOlLjkAdhA-29-gwYlfU&e=> @christianboyle<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_christianboyle&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=EKkWq-PIwclXaajKqY3DZrDQ9bdhdNRJkYhOAtxknFo&m=UcZXQ70t8qQukcYZ5YZ0J6v1gXlLLzvDhdQh1HtNB3mmMJPL5Al2C362p79qFDPp&s=WC623NEV0jRTUNAyKG1Nh2ePrE_p6EoPqaJ_RfdiTV0&e=> I was trying to get this in with a few other things, but the other things aren't quite ready yet. I shelved those and released a version with just this, it's available now.

**Comment by spalt** [comment]
@JDogg016 yes, redownload same as when you installed it... when you click it to install it will instead prompt you to update.

**Comment by christianboyle** [comment]
@spalt You rule, thanks so much!
