### ISSUE TITLE
Random Dimming

### ISSUE THREAD

**Issue by Dugans** [spalt/EO1#16]
Even with latest update, I still experience random dimming (it just comes and goes).  Pressing the side button restores brightness for awhile.  Don't know if this is software or hardware issue.  If it's just me experiencing this, must be hardware issue.

Otherwise a great app.

**Comment by christianboyle** [comment]
Yea, I'm experiencing that now too, but didn't prior to `0.0.6`.

**Comment by chrisdrackett** [comment]
I've been having issues with dimming since the first version, fwiw

**Comment by benadamson** [comment]
Me too

**Comment by wasauce** [comment]
Any solution here?

@aphex3k did you find a solution -- looking at your repo I saw some brightness related changed. Maybe I just adjust the minimum brightness during quite times to be same as max in the code?

**Comment by wasauce** [comment]
Referencing https://github.com/spalt/EO1/commit/f2be99b7ebbc1ddd9a709df9c9bb921733b04563

**Comment by spalt** [comment]
@wasauce @aphex3k if that works, I can implement it in my repo.  unfortunately my screen broke, and something happened to the light sensor while I was replacing it and no longer gives me any light values.  so i can't test changes to this particular bit of code....

**Comment by aphex3k** [comment]
Unfortunately I have yet to find a solution to actually turn of the screen...

**Comment by aphex3k** [comment]
I was convinced it would turn it off completely. Now that you say otherwise I am not so sure anymore... It would explain why I haven't gotten it working on all my test android tablets except the actual EO1 frames...

**Comment by spalt** [comment]
> I'd rather mine just stay on all the time then what I have now where unless I update the content its dimmed so much I can't see what is being displayed

@chrisdrackett  have you tried not using the auto-brightness feature and just set a brightness?

**Comment by chrisdrackett** [comment]
I have auto brightness off, I've tried everything but can't get things to display for more than about a day before the screen goes dim and stays that way till I wake it via a keyboard

**Comment by sangh** [comment]
So, the code should be fixed, but I will just mention that the way I got around this was that I had an rpi that I have running all the time in my place send a preferences update every 5 mins during the time I want to display to be on setting the brightness to 100%.

I just used a cronjob that runs this bash snippet:

    echo "options,1.0,${disp_secs},${off_hour},${on_hour}" | nc ${eo1_ip} 12345

**Comment by wasauce** [comment]
> So, the code should be fixed, but I will just mention that the way I got around this was that I had an rpi that I have running all the time in my place send a preferences update every 5 mins during the time I want to display to be on setting the brightness to 100%.
> 
> I just used a cronjob that runs this bash snippet:
> 
> ```
> echo "options,1.0,${disp_secs},${off_hour},${on_hour}" | nc ${eo1_ip} 12345
> ```

Thanks for this @sangh - I will setup the same.

**Comment by spalt** [comment]
to (possibly) address the random dimming I will re-set the brightness level each time a new item is displayed in the next version (coming soon).  not sure why this is affecting people who aren't using auto-brightness, but hopefully this will be somewhat of a fix.

i still am not totally sure about the auto-dimming algorithm and, like I said, my light sensor is no longer working so I can't really tell if any tweaks i am making are helping or hurting.

**Comment by chrisdrackett** [comment]
I don't ever display a "next" item, I've wondered if that is the reason. I basically show a single thing for up to a week at a time

**Comment by spalt** [comment]
@chrisdrackett you use the partner app to do that, to show an item from flickr?  or just set a really long slideshow interval?

**Comment by chrisdrackett** [comment]
I use the partner app because I have had bad to no luck using tags in flickr. I tag a single item and it sometimes works (never for videos however)

**Comment by spalt** [comment]
@chrisdrackett once you display an item, the slideshow "pauses", so i wonder if the OS is thinking nothing is happening and dims it automatically.  not sure what the solution is but i'll try and poke at it and see if i see something similar.

not to beat a dead horse, but when you go to upload things to Flickr, do you go through this process:
![image](https://github.com/spalt/EO1/assets/2190693/304689d4-fdef-446a-b5ea-5152cacf3ff9)
here i've dragged 4 items and clicked "Add Tags" and typed something distinctive.   (then I click upload 4 photos at the top right)

**Comment by chrisdrackett** [comment]
well, I want to only show a single item at a time, so I'm adding a tag to a single image or video and removing it from everything else. I think this is a flickr bug however, because when I go to the tag page often its empty even if the tag is clearly set on a given video.

I feel like I should look into the bash script above to poke the frame every once and a while. I wonder also if this is something we could build into the app somehow
