### ISSUE TITLE
Stuck on opening a web browser

### ISSUE THREAD

**Issue by wasauce** [spalt/EO1#17]
Hi!

Thank you very much for your work and instructions to get the EO1 functional again. I greatly appreciate it.

I have been working to try to follow the steps outlined in the README.

I get to "Getting Art" dialog, hit WINDOWS + B to open a web browser and I am stuck.

I have tried multiple different keyboards (windows and mac keyboards) and I have tried hitting the keys at different moments in the booting process  vs what I think is the stuck part of "getting art". Do you have any tips?

Below are screenshots of where I am trying to hit "WINDOWS + B" and running into the problem. Is the issue that I am not actually at the "Getting Art" screen and I am stuck because the EO1 cannot connect to the wifi?

Is there a more exhaustive list of keyboard shortcuts I can try to bring something up?

![IMG_2394](https://github.com/spalt/EO1/assets/41729/098d5a2e-b90a-4505-aa92-9946b5be0e7e)

![IMG_2392](https://github.com/spalt/EO1/assets/41729/f4aac5d1-7c34-4189-be26-22e5c61342fc)

![IMG_2390](https://github.com/spalt/EO1/assets/41729/3e91c8ed-413a-4ea9-b301-5b4ab2a87a2d)

![IMG_2391](https://github.com/spalt/EO1/assets/41729/60170b71-bd7c-49d8-9365-57d050a577e6)

Thank you again!

**Comment by spalt** [comment]
Hi there!  Yeah, the steps in the readme only work on a fully set up EO1, and this one appears to have been factory reset.  You may want to post your question on the reddit page, there are some real knowledgeable people there who may be able to help... https://www.reddit.com/r/electricobjects/
Good luck!

**Comment by wasauce** [comment]
@spalt really appreciate the reply. Thank you!

**Comment by iangilman** [comment]
@wasauce I have a similar problem. I've posted my question here: https://www.reddit.com/r/electricobjects/comments/188w596/eo1_how_to_open_web_browser_when_windows_b_doesnt/
