### ISSUE TITLE
install via built in browser does not always work

### ISSUE THREAD

**Issue by chrisdrackett** [spalt/EO1#4]
might be worth adding instructions to install firefox? Happy to do this unless I'm missing something about making the built in browser work.

**Comment by spalt** [comment]
@chrisdrackett specifying the github URL (should) work, i've noticed the built-in browser has an issue where downloads stall, the icon disappears, but then re-appears when its done... but I can investigate more.

**Comment by chrisdrackett** [comment]
no worries, I tried a lot and didn't have any luck before moving to firefox, but who knows!

**Comment by Dugans** [comment]
I could sure use a clue or two on moving to firefox!  Have had no luck with installed browser.  Thanks

**Comment by spalt** [comment]
FYI...  I've added a link to a mirror on the main github page that should work better on the glitchy device browser!
